version: "3.8"
services:
    # PHP service
    app:
        build: .
        working_dir: /var/www/
        ports:
            - "5173:5173"
        volumes:
            - ./:/var/www
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - app-network
    # MySQL database service
    db:
        platform: linux/amd64
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        networks:
            - app-network
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
    # Nginx service
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
volumes:
    dbdata:
        driver: local
networks:
    app-network:
        driver: bridge
